### PR TITLE
refactor: use js version of blake-hash

### PR DESCRIPTION
**Pull request by RichAyotte**
Use `js` version of `blake-hash`

### CODE REVIEW

**Comment by feri42** [comment]
How can we verify that the inputs and outputs are indeed compatible?

**Comment by RichAyotte** [comment]
@feri42 The hash will be different, but I'm not sure how important that is here. What do you think?

The types are also different, `blake3` returns `Uint8Array(32)` and `blake-hash` returns `Buffer(32)` but that's an easy fix, I can wrap the output with `Buffer.from()`. 

Here's a sample output.
```
Uint8Array(32) [ 10, 103, 128, 101, 230, 25, 129, 216, 187, 1, 50, 174, 253, 205, 126, 183, 193, 164, 84, 101, 51, 104, 170, 62, 250, 6, 227, 168, 95, 243, 247, 89 ]
Buffer(32) [ 173, 46, 126, 236, 19, 13, 16, 49, 233, 246, 156, 137, 128, 101, 157, 140, 80, 95, 248, 215, 211, 59, 137, 127, 165, 220, 46, 138, 220, 213, 220, 91 ]
```

I'm leaning towards going back to `blake-hash/js` because it's the safer option.

**Comment by RichAyotte** [comment]
Reverted back to using `blake-hash/js`

**Comment by feri42** [comment]
> The hash will be different, but I'm not sure how important that is here. What do you think?

Isn't it an immediate show-stopper if the hash is different?

**Comment by RichAyotte** [comment]
It could be, but not necessarily. That's why I reverted the blake3 changes back to the js version of blake-hash.

**Review by ChALkeR — APPROVED** [review]
utACK

@feri42 this is what we already do

`/index.js` just re-exports `/js.js` when it detects that no bindings are available

**Review by feri42 — APPROVED** [review]
utACK

**Comment by fboucquez** [comment]
The lib is only used [here](https://github.com/ExodusMovement/assets/blob/fccf8c75ebc3fa2e1de2a14803e979e3565b65f4/bitcoin/decred-plugin/src/get-dcrcore.js#L10-L16) and we have several tests [here](https://github.com/ExodusMovement/assets/blob/0cbfb9b3095955b259599359641d604cc2336c9e/bitcoin/decred-plugin/src/__tests__). We could run a quick sanity check by running the unit tests the change in the plugin

**Review by fboucquez — APPROVED** [review]
utACK (test are passing after a local change)

**Pull request merged**
